### ISSUE TITLE
Proposal Dependency fix that for me caused test to not appear

### ISSUE THREAD

**Issue by doozMen** [doozMen/Quick#1]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

1. I moved all framework search paths for all targets up to the project and rest inherits
2. I added `$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)` so it looks for the right framework for that platform and the build configuration (Debug / Release)
3. Added XCTest as an explicit linked dependency to every target
4. Made the target swift_version = 4.2 for every target

### TODO

* [x] Added example integration with subproject approach
* [x] Made a dependend build on Nimble via Carthage with submodule

### Project that demonstrates the issue
// TODO
Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).
